proejto_nova-versao/models/usuario.py
class User:
    def __init__(self, username, password):
        self.username = username
        self.password = password

    def validate(self, username, password):
        return self.username == username and self.password == password

proejto_nova-versao/app.py
from flask import Flask
from controllers.test import hello_controller

app = Flask(__name__)
app.register_blueprint(hello_controller)
app.secret_key = 'chave'

if __name__ == '__main__':
    app.run(debug=True)

proejto_nova-versao/controllers/login.py
from flask import render_template, redirect, url_for, request, session, Blueprint

proejto_nova-versao/controllers/test.py
from flask import Blueprint, request, url_for, redirect, render_template, session, flash
from models.usuario import User

Adm = User("ADM", "senhaforte")
Usuario1 = User("peixe", "1234")
lista = [Adm, Usuario1]

hello_controller = Blueprint('hello', __name__)


@hello_controller.route('/', methods=['POST', 'GET'])
def index():
    usuario_logado = session.get('usuario_logado')
    return render_template('home.html', usuario=usuario_logado)

@hello_controller.before_request
def autenticar_usuario():

    rota_protegida = request.endpoint in ['hello.protected']

    if rota_protegida and 'usuario_logado' not in session:
        flash("Você precisa estar logado para acessar essa página.")
        return redirect(url_for('hello.login'))

# parte de login

@hello_controller.route('/login', methods=['POST', 'GET'])
def login():
    # lógica?
    if request.method == "POST":
        session['usuario'] = request.form['username']
        return redirect(url_for('hello.index'))
    return render_template('login.html')

@hello_controller.route('/autenticar', methods=["POST"])
def autenticar():
    username = request.form['username']
    password = request.form['password']

    for usuario in lista:
        if usuario.validate(username, password):
            session['usuario_logado'] = usuario.username
            flash(f'{usuario.username} logado com sucesso!')
            return redirect(url_for('hello.index'))

    flash('Usuário ou senha incorretos.')
    return redirect(url_for('hello.login'))
   
@hello_controller.route('/logout')
def logout():
    session.pop('usuario_logado', None)
    return redirect(url_for('hello.login'))


@hello_controller.route('/compras')
def compras():
    return render_template('compras.html')

@hello_controller.route('/sistema')
def sistema():
    return render_template('sistema.html')

proejto_nova-versao/templates/compras.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Compras</title>
</head>
<body>
    <h1>Bem-vindo as compras!</h1>
</body>
</html>

proejto_nova-versao/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

    {% if usuario %}
        <h1>Bem-vindo, {{ usuario }}!</h1>
        <p><a href="{{ url_for('hello.logout') }}">Logout</a></p>
    {% else %}
        <h1>Bem-vindo a página principal!</h1>
        <p><a href="{{ url_for('hello.login') }}">Login</a></p>
    {% endif %}
</body>
</html>

proejto_nova-versao/templates/login.html
<!DOCTYPE html>
<html lang="pt-BR">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Livrinhos</title>
    <link href="https://fonts.googleapis.com/css2?family=Comfortaa:wght@300;400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg
    5GT6L4JJg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>

<body>
    <div class="container">
        <div class="form-section">
            <h2>Login</h2>
            <form action="{{url_for('hello.autenticar')}}" method="POST">
                <label for="campo1">Usuário:</label>
                <input type="text" id="usuario" name="username" required placeholder="Digite o seu usuário">
                <br>

                <label for="campo2">Senha:</label>
                <input type="password" id="senha" name="password" required placeholder="Digite a sua senha">

                <button type="submit" class="btn-add">Cadastrar</button>
            </form>
            <br>
            <a href="{{url_for('hello.index')}}">Voltar</a>
            {% with messages = get_flashed_messages() %}
                {% if messages %}
                <a class=flashes>
                {% for message in messages %}
                    <p>{{ message }}</p>
                {% endfor %}
                </a>
                {% endif %}
            {% endwith %}
            {% block body %}{% endblock %}
        </div>
    </div>
</body>

</html>

proejto_nova-versao/templates/sistema.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sistema</title>
</head>
<body>
    <h1>Acesso restrito.</h1>

</body>
</html>